### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by chinaxiaoyy** [o2team/react-native-web-demo#1]
安装html-webpack-plugin失败,提示是
Unexpected end of input at 1:32894
ncss":"./bin/cleancss"},"directories":{},"dist":{"shasum":"8cbe834ca8

这个怎么办啊?单独安装这个插件也是失败

**Comment by chuyik** [comment]
@chinaxiaoyy 可以试试先删除 npm 缓存，并使用淘宝源安装。
你这个问题跟我们项目没关系，可以到 html-webpack-plugin 或 npm 项目问问。

**Comment by chinaxiaoyy** [comment]
it  works,多谢
